# Generated by Django 3.2.8 on 2021-10-24 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('external_url', models.TextField()),
                ('image', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_type', models.TextField()),
                ('value', models.TextField()),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='nfttoken.metadata')),
            ],
        ),
    ]
