# Generated by Django 3.2.4 on 2021-10-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
                ('description', models.TextField(null=True)),
                ('external_url', models.TextField(null=True)),
                ('image', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to='post')),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_type', models.TextField()),
                ('value', models.TextField()),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='nfttoken.metadata')),
            ],
        ),
    ]
