# Generated by Django 3.2.8 on 2021-10-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfttoken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
    ]
