# Generated by Django 3.2.8 on 2021-10-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfttoken', '0002_metadata_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='post')),
            ],
        ),
    ]
