# Generated by Django 3.2.8 on 2021-10-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfttoken', '0003_nftimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftimage',
            old_name='cover',
            new_name='file',
        ),
    ]
